apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: cert-manager
spec:
  chart:
    name: cert-manager
    chartVersion: "v1.13.3"
  releaseName: cert-manager
  weight: -10
  exclude: 'repl{{ ne Distribution "embedded-cluster" }}'
  helmUpgradeFlags:
    - --wait
    - --timeout
    - 5m
  values:
    installCRDs: true
    global:
      imagePullSecrets:
        - name: '{{repl ImagePullSecretName }}'