apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: ingress-nginx
spec:
  chart:
    name: ingress-nginx
    chartVersion: "4.13.2"
  releaseName: ingress-nginx
  weight: -20
  helmUpgradeFlags:
    - --wait
    - --timeout
    - 5m
  optionalValues:
    # Only deploy nginx-ingress in embedded cluster
    - when: 'repl{{ ne Distribution "embedded-cluster" }}'
      recursiveMerge: false
      values: {}
  values:
    controller:
      service:
        type: NodePort
        nodePorts:
          http: "80"
          https: "443"
      image:
        digest: ""
        digestChroot: ""
      admissionWebhooks:
        patch:
          image:
            digest: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-registry
  namespace: default
stringData:
  .dockerconfigjson: repl{{ ImagePullSecretValue }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: kots.io/v1beta1
kind: OptionalResource
metadata:
  name: ingress-nginx-chart
spec:
  when: 'repl{{ eq Distribution "embedded-cluster" }}'