apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: ingress-nginx
spec:
  chart:
    name: ingress-nginx
    chartVersion: "4.13.2"
  releaseName: ingress-nginx
  weight: -20
  exclude: 'repl{{ ne Distribution "embedded-cluster" }}'
  helmUpgradeFlags:
    - --wait
    - --timeout
    - 5m
  values:
    imagePullSecrets:
      - name: '{{repl ImagePullSecretName }}'
    controller:
      service:
        type: NodePort
        nodePorts:
          http: "80"
          https: "443"