apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: ingress-nginx
spec:
  chart:
    name: ingress-nginx
    chartVersion: "4.13.2"
  releaseName: ingress-nginx
  weight: -20
  exclude: 'repl{{ ne Distribution "embedded-cluster" }}'
  helmUpgradeFlags:
    - --wait
    - --timeout
    - 5m
  values:
    imagePullSecrets:
      - name: '{{repl ImagePullSecretName }}'
    global:
      image:
        registry: images.alexparker.info/proxy/harbor-enterprise/k8s
    controller:
      service:
        type: NodePort
        nodePorts:
          http: "80"
          https: "443"
      admissionWebhooks:
        patch:
          image:
            image: ingress-nginx/kube-webhook-certgen
    defaultBackend:
      image:
        image: defaultbackend-amd64