{{- if .Values.global.replicated.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: replicated-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.replicated.dockerconfigjson }}
{{- end }}
